### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by bajtos** [mockyeah/mockyeah#137]
Hello, I came across your project while looking for an easy tool that will allow me to record snapshots of REST services and play them back in my tests. The project looks very promising, unfortunately it does not come with any license, which means it effectively cannot be used :(

Could you please add LICENSE (or LICENSE.md) file? You can do that easily via GitHub UI here:

https://github.com/mockyeah/mockyeah/community/license/new?branch=master

**Comment by ryanricard** [comment]
Thanks for the feedback, @bajtos. PR https://github.com/mockyeah/mockyeah/pull/138 licenses the project with MIT. It will be included in the next release slated for today. Let us know if you have additional questions.

**Comment by bajtos** [comment]
Great, thank you! At the end, I decided I want a slightly different solution for my integration tests (see https://github.com/strongloop/loopback-next/tree/master/packages/http-caching-proxy), thus I am not going to use your project.
