### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by KJLJon** [mockyeah/mockyeah#142]
There are a few issues when trying to run this on windows.

1. [ ] invalid characters for the file it tries to save ```\ / : * ? " < > |```.
    * just not sure what characters should be used that will make it still easy to read as a url 😃, maybe ```!``` which would make ```http://www.example.com/api/users``` turn into ```http!!!www.example.com!api!users```: https://github.com/mockyeah/mockyeah/blob/ef3481da0649a25c2659b7fe864ba9fe7da5a30a/app/lib/CaptureRecorder.js#L49-L52

    * and its test: https://github.com/mockyeah/mockyeah/blob/cd6d4ce71661fbda2f2c80a074393f679da361d4/test/integration/CaptureRecordAndPlayTest.js#L64-L67

2. [ ] windows isn't playing well with the multi-lined exec inside [ConfigTest.js](https://github.com/mockyeah/mockyeah/blob/cd6d4ce71661fbda2f2c80a074393f679da361d4/test/integration/ConfigTest.js)

One way I was able to get around it was to create a new file for each test (I can create a PR if you would like) and run it through a single line exec:
```js
function execTestJs(file, callback) {
  const scriptsPath = `${__dirname}${path.sep}..${path.sep}scripts${path.sep}`;
  return exec(`"${process.execPath}" "${scriptsPath}${file}"`, callback);
}
```

**Comment by ryanricard** [comment]
Thanks for the feedback, @KJLJon! We're in the process of working on redesigning how snapshots are written. Rather than a named directory with a set of crudely named JSON files, we're planning to have a single JSON file with an array of service captures; this should solve recording issues on Windows. This change should land in the next couple weeks.

**Comment by AndersDJohnson** [comment]
The file name issue at least is resolved in the latest versions of 0.x and 1.x due to directories being based on mock suite name now. I'm not sure about Windows support generally, though I wouldn't necessarily expect to see any issues.
