### ISSUE TITLE
Review package.json keywords

### ISSUE THREAD

**Issue by ryanricard** [mockyeah/mockyeah#36]
Why are more people not finding mockyeah? Are there keywords that should be added? How do the keywords for related projects compare?

**Comment by ajfuller** [comment]
Also worth adding github topics: https://help.github.com/articles/classifying-your-repository-with-topics/

**Comment by AndersDJohnson** [comment]
@ajfuller @ryanricard I've added some GitHub topics to this repo. Feel free to review and clean up or make suggestions for me to do so.

**Comment by KJLJon** [comment]
What about posting it on [hacker news](https://news.ycombinator.com/submit)?

**Comment by ryanricard** [comment]
Hacker News is a great idea, @KJLJon! We're really close to having the API and CLI finalized, there are a few remaining changes and fixes remaining before we're ready for v1. I anticipate we will be ready for a Hacker News post in the next 4-5 weeks. I would hate to post prematurely and have people endure issues like #142 😞

**Comment by AndersDJohnson** [comment]
After some additional ones I believe we added a while back, and #235, I think we can close this issue. Since the feature set keeps growing, and we've yet to advertise or evalgenize this repo, I don't think the keywords are the main prohibitive issue to discoverability.
