### ISSUE TITLE
Support fixture transform function for mock services

### ISSUE THREAD

**Issue by AndersDJohnson** [mockyeah/mockyeah#43]
Sometimes it's useful to start with a base fixture file but transform it slightly to be relevant to the current test. Rather than requiring us to manually read & parse the file then use `json`, why not offer a fixture transform function option to be used optionally alongside existing `fixture` option?

Relates to #403.

**Comment by ryanricard** [comment]
Thank you for submitting an issue, @AndersDJohnson. Interesting suggestion. Do you have a sudo code example for what you are envisioning?

**Comment by AndersDJohnson** [comment]
@ryanricard maybe:
```js
mockyeah.get('/products/:id', {
  fixture: 'product.json',
  fixtureTransform: fixture => ({
    ...fixture,
    id: '123'
  })
})
```
or:
```js
mockyeah.get('/products/:id', {
  fixture: ['product.json', fixture => ({
    ...fixture,
    id: '123'
  })]
})
```

**Comment by AndersDJohnson** [comment]
We already added support for dynamic response fixtures and support async functions, so technically this can be done already in Node and on client with Webpack. But we'll implement a formal feature for it with #403 - it can the same API for both fixtures and proxied responses.
