### ISSUE TITLE
Questions, multi-server, example, inspiration

### ISSUE THREAD

**Issue by tcrowe** [mockyeah/mockyeah#484]
Good day 👋 

I'm enjoying using some of the basic functionality on mockyeah so far. I wonder if you can help me use it for some more advanced cases now. 🤞 

I'm writing an HTTP server that uses resources on other HTTP servers, local or remote.

## Multi-server

I saw here it's setting up a `.get` for a domain. I'm using superagent so I can have it set the `Host:` header to the mockyeah server(s). Am I on the right track there?
https://mockyeah.js.org/Configuration.html#options

I'm setting up different directories in fixtures for these other servers in preparation.

+ ./test/fixtures/couchdb/{database}/{docId}
+ ./test/fixtures/s3/{bucket}/{docId}
+ ./test/fixtures/payment-service1/*
+ ./test/fixtures/payment-service2/*

Is this the recommended way to setup mock responses for these?

Do I need one mockyeah server or multiple?

Can I have mockyeah record requests into those places, even if no mock response exists yet, so I can fill it out later? Or would it record into `suitesDir`?

I hope you can understand the goal even if I'm not yet approaching it in the most efficient way.

## Admin

How do I use the admin and what does it do? 🤔 

## Examples & inspiration

Are there some public projects I can browse to see ways other people are using mockyeah?

---

Thank you!
-Tony

**Comment by tcrowe** [comment]
Using the new github packages feature we have some answers. NPM doesn't have these.
https://github.com/mockyeah/mockyeah/network/dependents?package_id=UGFja2FnZS0xNDkzNzMwNA%3D%3D

**Comment by AndersDJohnson** [comment]
> Good day 👋
> 
> I'm enjoying using some of the basic functionality on mockyeah so far. I wonder if you can help me use it for some more advanced cases now. 🤞

Great to hear!

> I'm writing an HTTP server that uses resources on other HTTP servers, local or remote.
> 
> ## Multi-server
> I saw here it's setting up a `.get` for a domain. I'm using superagent so I can have it set the `Host:` header to the mockyeah server(s). Am I on the right track there?
> https://mockyeah.js.org/Configuration.html#options

You would want to setup your app to point requests to the mockyeah server URL as a prefix to the actual URLs. With the default `host` and `port` in mockyeah configuration, e.g., http://localhost:4001/http://example.com.

> I'm setting up different directories in fixtures for these other servers in preparation.
> 
> * ./test/fixtures/couchdb/{database}/{docId}
> * ./test/fixtures/s3/{bucket}/{docId}
> * ./test/fixtures/payment-service1/*
> * ./test/fixtures/payment-service2/*
> 
> Is this the recommended way to setup mock responses for these?

That should work just fine, if you set `fixturesDir` to `./test/fixtures` in config (it defaults to `./fixtures`)! Make sure you also define some `index.js` files in folders under `suitesDir` (default `./mockyeah`) and from there you can `require('../test/fixtures/whatever')` as `json` option in the response options of your mocks. See example here: https://github.com/mockyeah/mockyeah/blob/master/packages/mockyeah/test/mockyeah/some-custom-suite-2/index.js

> Do I need one mockyeah server or multiple?

One should be fine. If you want, you can play different suites at different times, or use another means to opt-in, such as adding a unique custom header to `headers` in the match options of each of your suites, or the dynamic opt-in functionality (https://github.com/mockyeah/mockyeah/pull/240 undocumented feature as-of-yet).

> Can I have mockyeah record requests into those places, even if no mock response exists yet, so I can fill it out later? Or would it record into `suitesDir`?

It would record suite `index.js` files to `suitesDir` but put associated fixtures in your `fixturesDir` folder which you could set to `./test/fixtures`.

> I hope you can understand the goal even if I'm not yet approaching it in the most efficient way.
> 
> ## Admin
> How do I use the admin and what does it do? 🤔

The admin server runs in the background and lets us talk to it dynamically to play and record suites via the CLI commands.

> ## Examples & inspiration
> Are there some public projects I can browse to see ways other people are using mockyeah?
> 
> Thank you!
> -Tony

I suppose, as you found, https://github.com/mockyeah/mockyeah/network/dependents?package_id=UGFja2FnZS0xNDkzNzMwNA%3D%3D

Also consider reviewing the [tests](https://github.com/mockyeah/mockyeah/tree/master/packages/mockyeah/test) and [examples](https://github.com/mockyeah/mockyeah/tree/master/packages/mockyeah/examples).

**Comment by tcrowe** [comment]
I put all your suggestions and tips to use and learned *the ways.* 💪😁

Is it possible we can leave it open a few days in case I am in need of more tutelage?

**Comment by tcrowe** [comment]
I've gotten the hang of it. Thank you for your help and I look forward to the new site and updates you're making. 👍🏻
