### ISSUE TITLE
Contributing: lerna bootstrap

### ISSUE THREAD

**Issue by tcrowe** [mockyeah/mockyeah#487]
Just in case people don't know it might help contributors spin up the project if we add `lerna bootstrap` in there. [The Travis CI config](https://github.com/mockyeah/mockyeah/blob/master/.travis.yml#L8) does it but not `./package.json` or `./packages/mockyeah-docs/src/pages/Contributing.md`.

There's a few options.
+ `./package.json#scripts.postinstall`
+ Contributing.md says `npm install && ./node_modules/.bin/lerna bootstrap`

I'm happy to make the PR if you want this info added somewhere.

**Comment by tcrowe** [comment]
Also `npm start`

**Comment by AndersDJohnson** [comment]
@tcrowe Good idea. Would love to see a PR if you're willing!
