### ISSUE TITLE
Document response api anonymous function support

### ISSUE THREAD

**Issue by ryanricard** [mockyeah/mockyeah#5]

**Comment by akrawchyk** [comment]
Does this mean we can form responses like this?

```javascript
mockyeah.get('/america', {
  json: (req) => {
    const state = req.query.state

    if (state) {
      return { success: state }
    } else {
      return { error: 'not today' }
    }
  },
  latency: 500
});
```

**Comment by AndersDJohnson** [comment]
@akrawchyk I don't think that is supported yet, but I think it's a great idea, so opened #100 implementing it as a new feature. CC @ryanricard

**Comment by AndersDJohnson** [comment]
I believe this was to document the custom middleware support, which was removed in #429 in order to help decouple from Express internally, so we'll close this issue.
