### ISSUE TITLE
Write v1 documentation 

### ISSUE THREAD

**Issue by ryanricard** [mockyeah/mockyeah#70]
* Document new param matching functionality
* Document proxy middleware behavior
* Consider creating Gitbook documentation site to house v1 and pre v1 documentation

**Comment by AndersDJohnson** [comment]
Relates to #51.

**Comment by AndersDJohnson** [comment]
@ryanricard Would you prefer Gitbook hosted in this repo, or external repo? We might move to monorepo for the CLI, etc.

**Comment by ryanricard** [comment]
I am fine with either, monorepo may be easier to manage in the short term. i.e. feature and documentation changes included in same pull requests.

**Comment by ryanricard** [comment]
@AndersDJohnson I can take over the documentation writing now that we have GitBook deployed. I am pretty busy this weekend, but should be able to make progress next week. Thoughts?

**Comment by AndersDJohnson** [comment]
@ryanricard That's cool. I can do some of it too if you like.

**Comment by ryanricard** [comment]
Thoughts on information architecture? I like the API Reference section on https://redux.js.org/, Lodash documentation is similar providing immediate visibility to the api.

Thoughts on the following layout? Anything missing? Or any changes that come to mind?

* Introduction
  * Getting started
* API
* Recipes/Examples

**Comment by AndersDJohnson** [comment]
Relates to #5.

**Comment by AndersDJohnson** [comment]
@ryanricard Most of the methods you have under "Service API" have identical function signatures. Does it still make sense to have separate pages documenting them?
