### ISSUE TITLE
Create a project logo

### ISSUE THREAD

**Issue by ryanricard** [mockyeah/mockyeah#80]

**Comment by ajfuller** [comment]
Any initial images that come to your mind when you think of mockyeah?

**Comment by ajfuller** [comment]
Was playing around with some colors and shapes to kick things off:

<img src="https://user-images.githubusercontent.com/2483304/36626395-05e5996e-1900-11e8-88c0-4881bf7e573a.png" width="200" />

**Comment by ryanricard** [comment]
Oooo, cool! My initial impressions: 
* The project helps make things "check out". 
* Two checkmarks represent two integrated systems, with the border/filled checkmark being mockyeah.
* Gives me a sense of successful assertion.

The initial images that came to mind were a composition of initials M and Y. Nevertheless, I wanted to gravitate toward something more abstract. It would be nice to arrive at a logo that would look good on stickers and t-shirts. We are headed in the right direction with your initial mockup 👍

**Comment by AndersDJohnson** [comment]
Some ideas:

![6308381748887552](https://user-images.githubusercontent.com/615381/36636674-9e70f6a2-1990-11e8-891c-e6fe2baa5550.png)


![5686361499631616](https://user-images.githubusercontent.com/615381/36636646-3dd7afde-1990-11e8-8fa2-7a0990af5849.png)

**Comment by ajfuller** [comment]
Was thinking the same but maybe using the y to create a check mark across the m?

**Comment by AndersDJohnson** [comment]
@ajfuller Updated with a few more ideas.

**Comment by ajfuller** [comment]
Your third image reminds me of Mario and makes me happy, unfortunately I’m not near my cpu right now so I can’t twaek but I’ll try to send some additional ideas tomorrow

**Comment by ryanricard** [comment]
![screen shot 2018-02-26 at 9 15 35 am](https://user-images.githubusercontent.com/438435/36678160-a823f17c-1ad5-11e8-9624-c428dbc5f66b.png)

Thoughts on dropping the Y and altering @ajfuller original mockup to include an M? My alteration is very crude, but it will give you the idea.

**Comment by ryanricard** [comment]
I really kinda like the double check marks, without the M. @ajfuller and @AndersDJohnson, should we just go with it for now? We can revisit the design later. @ajfuller thoughts on producing some quality images?

**Comment by ajfuller** [comment]
Yeah I think it works nicely as a working logo. Here's some large squares that will work in the Github org picture

White BG
![mockyeah-white-bg](https://user-images.githubusercontent.com/2483304/36766577-7de0fa7e-1c04-11e8-87c2-32c84afb8b29.png)

Gray BG
![mockyeah-gray-bg 2x](https://user-images.githubusercontent.com/2483304/36766582-81c8ebd8-1c04-11e8-83dc-3740f248a8d4.png)

Only Checkmark
![mockyeah-checks-white-bg](https://user-images.githubusercontent.com/2483304/36766598-8d5cbe48-1c04-11e8-8a5a-a858dc4b8138.png)

**Comment by ryanricard** [comment]
Awesome! Thanks, @ajfuller! 

Closing for now. Feel free to continue to iterate and comment on this issue if you continue to have a creative itch on this subject.

**Comment by ryanricard** [comment]
Logo looks really good on the org, @ajfuller. I went with the gray background, let me know your thoughts; we can always swap out for the white background.

**Comment by ajfuller** [comment]
I like the gray, just figured I'd give you the option 😄
