### ISSUE TITLE
HTTPS support for http://mockyeah.js.org/

### ISSUE THREAD

**Issue by AndersDJohnson** [mockyeah/mockyeah#83]
We should figure out how to add HTTPS support to http://mockyeah.js.org/. I've done so with Cloudflare CDN and GitHub Pages before.

Relates to #81.

**Comment by AndersDJohnson** [comment]
See https://github.com/js-org/dns.js.org/pull/1804.

**Comment by AndersDJohnson** [comment]
We now have https://mockyeah.js.org/. I've updated the repository URL. We should consider adding a `homepage` key to the `package.json`.

**Comment by ryanricard** [comment]
@AndersDJohnson can we delete the dns.js.org fork?

**Comment by AndersDJohnson** [comment]
@ryanricard Yes. Doing it.
