### ISSUE TITLE
Create Twitter account

### ISSUE THREAD

**Issue by AndersDJohnson** [mockyeah/mockyeah#95]
For marketing purposes, a Twitter account could be good to grab. Too bad looks like https://twitter.com/mockyeah is already taken.

**Comment by ryanricard** [comment]
Registered @mockyeahjs. Thoughts on how we should manage multiple accounts and tweeting?

**Comment by AndersDJohnson** [comment]
@ryanricard what do you mean by how to manage multiple accounts? You mean between admins of the organization?

**Comment by ryanricard** [comment]
@AndersDJohnson, how do we manage the account across owner and contributors. Are there tools that make it easy to wrangle multiple accounts? Instagram has a feature that lets you swap between multiple account contexts. A lot of questions on how we should utilize twitter.

**Comment by AndersDJohnson** [comment]
@ryanricard We'll do some research and ideate on it. For now, I just wanted to camp the handle.
